#!/usr/bin/env bash

set -euo pipefail

export MY_DISK=/dev/nvme0n1
export MY_ROOT=luksroot
export LOGFILE=arch_install.log

# Redirect stdout and stderr to tee
exec > >(tee -a "$LOGFILE") 2>&1

if [[ ! -b "$MY_DISK" ]]; then
    echo "Error: $MY_DISK is not a valid block device."
    exit 1
fi

echo "This will ERASE all data on $MY_DISK!"
read -rp "Type 'YES' to continue: " confirm
[[ "$confirm" == "YES" ]] || exit 1

sgdisk --zap-all "$MY_DISK"
parted -s "$MY_DISK" mklabel gpt
parted -s "$MY_DISK" mkpart ESP fat32 1MiB 2049MiB
parted -s "$MY_DISK" set 1 esp on
parted -s "$MY_DISK" mkpart primary 2049MiB 100%

lsblk "$MY_DISK"
partprobe ${MY_DISK}

sgdisk -p ${MY_DISK}
cryptsetup luksFormat --type luks2 ${MY_DISK}p2

cryptsetup open ${MY_DISK}p2 ${MY_ROOT}

mkfs.vfat -F32 -n EFI ${MY_DISK}p1

mkfs.btrfs -f -L ${MY_ROOT} /dev/mapper/${MY_ROOT}

mount /dev/mapper/${MY_ROOT} /mnt

btrfs subvolume create /mnt/@
btrfs subvolume create /mnt/@home
btrfs subvolume create /mnt/@root
btrfs subvolume create /mnt/@cache
btrfs subvolume create /mnt/@log
btrfs subvolume create /mnt/@libvirt

btrfs subvolume list /mnt

umount /mnt

mount -t btrfs -o subvol=@,compress-force=zstd:1 -m /dev/mapper/${MY_ROOT} /mnt
mount -t btrfs -o subvol=@home,compress-force=zstd:1 -m /dev/mapper/${MY_ROOT} /mnt/home
mount -t btrfs -o subvol=@root,compress-force=zstd:1 -m /dev/mapper/${MY_ROOT} /mnt/root
mount -t btrfs -o subvol=@cache,compress-force=zstd:1 -m /dev/mapper/${MY_ROOT} /mnt/var/cache
mount -t btrfs -o subvol=@log,compress-force=zstd:1 -m /dev/mapper/${MY_ROOT} /mnt/var/log
mount -t btrfs -o subvol=@libvirt,compress-force=zstd:1 -m /dev/mapper/${MY_ROOT} /mnt/var/libvirt

mount -m ${MY_DISK}p1 /mnt/efi

reflector --country GB --age 24 --protocol http,https --sort rate --save /etc/pacman.d/mirrorlist

pacstrap -K /mnt base base-devel linux linux-firmware intel-ucode vim nano nvim cryptsetup btrfs-progs dosfstools util-linux git unzip sbctl networkmanager sudo

genfstab -U /mnt >> /mnt/etc/fstab
cat /mnt/etc/fstab

systemd-firstboot --root /mnt --prompt

arch-chroot /mnt locale-gen

arch-chroot /mnt groupadd sudo
arch-chroot /mnt useradd -G sudo -m h

arch-chroot /mnt passwd h
arch-chroot /mnt passwd root

# Uncomment the "%sudo ALL=(ALL:ALL) ALL" line
# arch-chroot /mnt visudo
sed -i 's/^# *%sudo/%sudo/' /mnt/etc/sudoers
arch-chroot /mnt visudo -c

# Get UUID for luks partition
export MY_UUID=$(blkid ${MY_DISK}p2 | sed -n 's/.*UUID="\([^"]*\)".*/\1/p')
echo $MY_UUID

# Configure /mnt/etc/cmdline.d/root.conf
mkdir /mnt/etc/cmdline.d
echo "rd.luks.name=${MY_UUID}=${MY_ROOT} root=/dev/mapper/${MY_ROOT} rootfstype=btrfs rootflags=subvol=/@ rw" > /mnt/etc/cmdline.d/root.conf

# Configure HOOKS in /etc/cmdline.d/root.conf
# vim /mnt/etc/mkinitcpio.conf
sed -i 's/^HOOKS=.*/HOOKS=(base systemd autodetect microcode modconf kms keyboard sd-vconsole sd-encrypt block filesystems fsck)/' /mnt/etc/mkinitcpio.conf

# Configure /mnt/etc/mkinitcpio.d/linux.preset
# vim /mnt/etc/mkinitcpio.d/linux.preset
cat > /mnt/etc/mkinitcpio.d/linux.preset <<'EOF'
# mkinitcpio preset file for the 'linux' package

ALL_config="/etc/mkinitcpio.conf"
ALL_kver="/boot/vmlinuz-linux"
ALL_microcode="/boot/intel-ucode.img"

PRESETS=('default' 'fallback')

#default_config="/etc/mkinitcpio.conf"
#default_image="/boot/initramfs-linux.img"
default_uki="/efi/EFI/Linux/arch-linux.efi"
default_options="--splash /usr/share/systemd/bootctl/splash-arch.bmp"

#fallback_config="/etc/mkinitcpio.conf"
#fallback_image="/boot/initramfs-linux-fallback.img"
fallback_uki="/efi/EFI/Linux/arch-linux-fallback.efi"
fallback_options="-S autodetect"
EOF

mkdir -p /mnt/efi/EFI/Linux
arch-chroot /mnt mkinitcpio -P

objdump -s -j .cmdline /mnt/efi/EFI/Linux/arch-linux.efi
ls -lR /mnt/efi

systemctl --root /mnt enable systemd-resolved systemd-timesyncd NetworkManager
systemctl --root /mnt mask systemd-networkd

arch-chroot /mnt bootctl install --esp-path=/efi
ls -lR /mnt/efi

sync

